version: '3.8'

services:
  rails:
    image: chatwoot/chatwoot:latest
    env_file: .env.production
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    networks:
      - traefik-public
      - internal
    volumes:
      - storage_data:/app/storage
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.chatwoot.rule=Host(`chatwoot.seudominio.com`)"
        - "traefik.http.routers.chatwoot.entrypoints=websecure"
        - "traefik.http.routers.chatwoot.tls=true"
        - "traefik.http.routers.chatwoot.tls.certresolver=letsencrypt"
        - "traefik.http.services.chatwoot.loadbalancer.server.port=3000"
        - "traefik.docker.network=traefik-public"
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']

  sidekiq:
    image: chatwoot/chatwoot:latest
    env_file: .env.production
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
    networks:
      - internal
    volumes:
      - storage_data:/app/storage
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']

  postgres:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_DB=chatwoot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - internal
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  redis:
    image: redis:alpine
    command: ["sh", "-c", "redis-server --requirepass \"${REDIS_PASSWORD}\""]
    networks:
      - internal
    volumes:
      - redis_data:/data
    deploy:
      restart_policy:
        condition: on-failure

networks:
  traefik-public:
    external: true
  internal:
    driver: overlay

volumes:
  storage_data:
  postgres_data:
  redis_data:
